# Generated by Django 4.0.3 on 2022-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
